# 1. Identificación del Microservicio
spring.application.name=NovaLogistic
server.port=8080


spring.datasource.url=jdbc:oracle:thin:@bdnovalogistic_high?TNS_ADMIN=C:/Users/darie/Downloads/Wallet_BDNOVALOGISTIC
spring.datasource.username=ADMIN
spring.datasource.password=Novalogistic4590
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# 3. Configuración de JPA / Hibernate
# Hibernate detecta automáticamente el dialecto de Oracle en Spring Boot 3.3
spring.jpa.show-sql=true

# ddl-auto=update intentará crear las tablas si no existen en tu bd_novalogistic
spring.jpa.hibernate.ddl-auto=update

# 4. Optimización de Conexión (HikariPool)
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=5

# 5. Configuración de Eureka (Opcional)
# Esto silencia los errores de "Connection refused" si no estás usando el servidor Eureka ahora
eureka.client.enabled=false

# 6. Manejo de JSON (Para evitar errores con fechas en Postman)
spring.jackson.serialization.write-dates-as-timestamps=false